version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y zlib1g-dev libbz2-dev default-jre
      - run:
          name: Install and deploy
          command: |
            cp config.yml.sample config.yml
            bundle install --path vendor/bundle
            bundle exec rake deploy:build
            echo $CIRCLE_SHA1 | cut -c1-7 > .build_rev
            tar jcf build.tar.bz2 * .build_rev .build_time
      - store_artifacts:
          path: /home/circleci/work/build.tar.bz2
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - /home/circleci/work/vendor/bundle

workflows:
  version: 2
  build:
    jobs:
      - build
